[package]
name = "pigment64"
description = "A library for handling conversion between N64 texture formats and modern image formats"
license = "MIT"
version = "0.2.2"
edition = "2021"

[dependencies]
png = "0.17.9"
clap = { version = "4.1.12", features = ["derive"] }
anyhow = "1.0.72"
byteorder = "1.4.3"
